### ISSUE TITLE
"webtoons.com" extension

### ISSUE THREAD

**Issue by uwu-wuw** [kodjodevf/mangayomi-extensions#117]
### Source name

webtoon

### Source link

https://www.webtoons.com/en/

### Source language

English

### Other details

I already made this extension and use it in my pc, but am not sure if I should pull request or not. Also, I don't know how to pull request.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/kodjodevf/mangayomi-extensions/) and verified it does not appear in the code base.

**Comment by NBA2K1** [comment]
How to make a pull request:
1. Fork the repo
2. clone your forked repo
3. add your Webtoons extension in the correct folder of your repo
4. git commit
5. git push
(Or instead of cloning, adding, committing, pushing, you can upload your extension directly in GitHub website)
6. Go to your repo's main page
7. Click on "Contribute"
8. Click on "Open pull request"

**Comment by uwu-wuw** [comment]
thanks for the help. I'm closing this issue now
